spring:
  datasource:
    password: P@ssword
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=DW_MART;trustServerCertificate=true
    username: SA
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: validate
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
